# Site settings
title: Reid Gaede
email: reid.gaede@gmail.com
url: https://reidgaede.github.io/
description: "Portfolio site for passionate front-end developer always looking for the next great challenge."
keywords: "Cincinnati, Front-End, Front-End Developer, Fulbright, React, ReactJS, HTML, CSS"
skills: "Software Developer - Self-Starter - Lifelong Learner"
meta_author: Gaede Reid

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# (6/5/23) Upon being reminded that GitHub Pages does NOT (to my knowledge) work with PHP, "un-commenting-out" 
# the `contact: static` line below this comment to reflect revised intention to use Formspree:
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# (6/4/23) Line below this comment "commented-out" in hopes it will help PHP-based "contact_me.php" to
# function correctly:
# disqus_shortname: myshortname

# (5/31/23) HERE (!!!) (seems) TO BE WHERE YOU ADJUST THE COLOR SCHEME (!!!):
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 212e3b #80B3FF # (5/31/23) Changed first value from 18bc9c to 212e3b.
  primary-rgb: "24,288,156" #"128,179,255" # (5/31/23) Not sure what to do with this at the moment.
  secondary: 03c49d #FD6E8A # (5/31/23) Changed first value from 2c3e50 to 03c49d.
  secondary-dark: 233140 #A2122F # (5/31/23) Changed first value from 233140 to 02a181.

# Footer settings
footer:
  copyright: Reid Gaede
  location: Location
  social: For More Info
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/reid-gaede/
  - title: github
    url: https://github.com/reidgaede

# Postal address (add as many lines as necessary)
address:
  - line: Cincinnati, OH
  - line: United States of America

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
